/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.acme.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class priceModifier extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3072589123874891635L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"priceModifier\",\"namespace\":\"com.acme.avro\",\"fields\":[{\"name\":\"promotionCode\",\"type\":\"string\"},{\"name\":\"partnerCode\",\"type\":\"string\"},{\"name\":\"promotionDiscount\",\"type\":\"string\"},{\"name\":\"staffDiscount\",\"type\":\"string\"},{\"name\":\"newPrice\",\"type\":\"string\"},{\"name\":\"promotionType\",\"type\":\"string\"},{\"name\":\"promotionDescription\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<priceModifier> ENCODER =
      new BinaryMessageEncoder<priceModifier>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<priceModifier> DECODER =
      new BinaryMessageDecoder<priceModifier>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<priceModifier> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<priceModifier> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<priceModifier>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this priceModifier to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a priceModifier from a ByteBuffer. */
  public static priceModifier fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence promotionCode;
  @Deprecated public java.lang.CharSequence partnerCode;
  @Deprecated public java.lang.CharSequence promotionDiscount;
  @Deprecated public java.lang.CharSequence staffDiscount;
  @Deprecated public java.lang.CharSequence newPrice;
  @Deprecated public java.lang.CharSequence promotionType;
  @Deprecated public java.lang.CharSequence promotionDescription;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public priceModifier() {}

  /**
   * All-args constructor.
   * @param promotionCode The new value for promotionCode
   * @param partnerCode The new value for partnerCode
   * @param promotionDiscount The new value for promotionDiscount
   * @param staffDiscount The new value for staffDiscount
   * @param newPrice The new value for newPrice
   * @param promotionType The new value for promotionType
   * @param promotionDescription The new value for promotionDescription
   */
  public priceModifier(java.lang.CharSequence promotionCode, java.lang.CharSequence partnerCode, java.lang.CharSequence promotionDiscount, java.lang.CharSequence staffDiscount, java.lang.CharSequence newPrice, java.lang.CharSequence promotionType, java.lang.CharSequence promotionDescription) {
    this.promotionCode = promotionCode;
    this.partnerCode = partnerCode;
    this.promotionDiscount = promotionDiscount;
    this.staffDiscount = staffDiscount;
    this.newPrice = newPrice;
    this.promotionType = promotionType;
    this.promotionDescription = promotionDescription;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return promotionCode;
    case 1: return partnerCode;
    case 2: return promotionDiscount;
    case 3: return staffDiscount;
    case 4: return newPrice;
    case 5: return promotionType;
    case 6: return promotionDescription;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: promotionCode = (java.lang.CharSequence)value$; break;
    case 1: partnerCode = (java.lang.CharSequence)value$; break;
    case 2: promotionDiscount = (java.lang.CharSequence)value$; break;
    case 3: staffDiscount = (java.lang.CharSequence)value$; break;
    case 4: newPrice = (java.lang.CharSequence)value$; break;
    case 5: promotionType = (java.lang.CharSequence)value$; break;
    case 6: promotionDescription = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'promotionCode' field.
   * @return The value of the 'promotionCode' field.
   */
  public java.lang.CharSequence getPromotionCode() {
    return promotionCode;
  }

  /**
   * Sets the value of the 'promotionCode' field.
   * @param value the value to set.
   */
  public void setPromotionCode(java.lang.CharSequence value) {
    this.promotionCode = value;
  }

  /**
   * Gets the value of the 'partnerCode' field.
   * @return The value of the 'partnerCode' field.
   */
  public java.lang.CharSequence getPartnerCode() {
    return partnerCode;
  }

  /**
   * Sets the value of the 'partnerCode' field.
   * @param value the value to set.
   */
  public void setPartnerCode(java.lang.CharSequence value) {
    this.partnerCode = value;
  }

  /**
   * Gets the value of the 'promotionDiscount' field.
   * @return The value of the 'promotionDiscount' field.
   */
  public java.lang.CharSequence getPromotionDiscount() {
    return promotionDiscount;
  }

  /**
   * Sets the value of the 'promotionDiscount' field.
   * @param value the value to set.
   */
  public void setPromotionDiscount(java.lang.CharSequence value) {
    this.promotionDiscount = value;
  }

  /**
   * Gets the value of the 'staffDiscount' field.
   * @return The value of the 'staffDiscount' field.
   */
  public java.lang.CharSequence getStaffDiscount() {
    return staffDiscount;
  }

  /**
   * Sets the value of the 'staffDiscount' field.
   * @param value the value to set.
   */
  public void setStaffDiscount(java.lang.CharSequence value) {
    this.staffDiscount = value;
  }

  /**
   * Gets the value of the 'newPrice' field.
   * @return The value of the 'newPrice' field.
   */
  public java.lang.CharSequence getNewPrice() {
    return newPrice;
  }

  /**
   * Sets the value of the 'newPrice' field.
   * @param value the value to set.
   */
  public void setNewPrice(java.lang.CharSequence value) {
    this.newPrice = value;
  }

  /**
   * Gets the value of the 'promotionType' field.
   * @return The value of the 'promotionType' field.
   */
  public java.lang.CharSequence getPromotionType() {
    return promotionType;
  }

  /**
   * Sets the value of the 'promotionType' field.
   * @param value the value to set.
   */
  public void setPromotionType(java.lang.CharSequence value) {
    this.promotionType = value;
  }

  /**
   * Gets the value of the 'promotionDescription' field.
   * @return The value of the 'promotionDescription' field.
   */
  public java.lang.CharSequence getPromotionDescription() {
    return promotionDescription;
  }

  /**
   * Sets the value of the 'promotionDescription' field.
   * @param value the value to set.
   */
  public void setPromotionDescription(java.lang.CharSequence value) {
    this.promotionDescription = value;
  }

  /**
   * Creates a new priceModifier RecordBuilder.
   * @return A new priceModifier RecordBuilder
   */
  public static com.acme.avro.priceModifier.Builder newBuilder() {
    return new com.acme.avro.priceModifier.Builder();
  }

  /**
   * Creates a new priceModifier RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new priceModifier RecordBuilder
   */
  public static com.acme.avro.priceModifier.Builder newBuilder(com.acme.avro.priceModifier.Builder other) {
    return new com.acme.avro.priceModifier.Builder(other);
  }

  /**
   * Creates a new priceModifier RecordBuilder by copying an existing priceModifier instance.
   * @param other The existing instance to copy.
   * @return A new priceModifier RecordBuilder
   */
  public static com.acme.avro.priceModifier.Builder newBuilder(com.acme.avro.priceModifier other) {
    return new com.acme.avro.priceModifier.Builder(other);
  }

  /**
   * RecordBuilder for priceModifier instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<priceModifier>
    implements org.apache.avro.data.RecordBuilder<priceModifier> {

    private java.lang.CharSequence promotionCode;
    private java.lang.CharSequence partnerCode;
    private java.lang.CharSequence promotionDiscount;
    private java.lang.CharSequence staffDiscount;
    private java.lang.CharSequence newPrice;
    private java.lang.CharSequence promotionType;
    private java.lang.CharSequence promotionDescription;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.acme.avro.priceModifier.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.promotionCode)) {
        this.promotionCode = data().deepCopy(fields()[0].schema(), other.promotionCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.partnerCode)) {
        this.partnerCode = data().deepCopy(fields()[1].schema(), other.partnerCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.promotionDiscount)) {
        this.promotionDiscount = data().deepCopy(fields()[2].schema(), other.promotionDiscount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.staffDiscount)) {
        this.staffDiscount = data().deepCopy(fields()[3].schema(), other.staffDiscount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.newPrice)) {
        this.newPrice = data().deepCopy(fields()[4].schema(), other.newPrice);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.promotionType)) {
        this.promotionType = data().deepCopy(fields()[5].schema(), other.promotionType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.promotionDescription)) {
        this.promotionDescription = data().deepCopy(fields()[6].schema(), other.promotionDescription);
        fieldSetFlags()[6] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing priceModifier instance
     * @param other The existing instance to copy.
     */
    private Builder(com.acme.avro.priceModifier other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.promotionCode)) {
        this.promotionCode = data().deepCopy(fields()[0].schema(), other.promotionCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.partnerCode)) {
        this.partnerCode = data().deepCopy(fields()[1].schema(), other.partnerCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.promotionDiscount)) {
        this.promotionDiscount = data().deepCopy(fields()[2].schema(), other.promotionDiscount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.staffDiscount)) {
        this.staffDiscount = data().deepCopy(fields()[3].schema(), other.staffDiscount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.newPrice)) {
        this.newPrice = data().deepCopy(fields()[4].schema(), other.newPrice);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.promotionType)) {
        this.promotionType = data().deepCopy(fields()[5].schema(), other.promotionType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.promotionDescription)) {
        this.promotionDescription = data().deepCopy(fields()[6].schema(), other.promotionDescription);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'promotionCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getPromotionCode() {
      return promotionCode;
    }

    /**
      * Sets the value of the 'promotionCode' field.
      * @param value The value of 'promotionCode'.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder setPromotionCode(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.promotionCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'promotionCode' field has been set.
      * @return True if the 'promotionCode' field has been set, false otherwise.
      */
    public boolean hasPromotionCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'promotionCode' field.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder clearPromotionCode() {
      promotionCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'partnerCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getPartnerCode() {
      return partnerCode;
    }

    /**
      * Sets the value of the 'partnerCode' field.
      * @param value The value of 'partnerCode'.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder setPartnerCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.partnerCode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'partnerCode' field has been set.
      * @return True if the 'partnerCode' field has been set, false otherwise.
      */
    public boolean hasPartnerCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'partnerCode' field.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder clearPartnerCode() {
      partnerCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'promotionDiscount' field.
      * @return The value.
      */
    public java.lang.CharSequence getPromotionDiscount() {
      return promotionDiscount;
    }

    /**
      * Sets the value of the 'promotionDiscount' field.
      * @param value The value of 'promotionDiscount'.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder setPromotionDiscount(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.promotionDiscount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'promotionDiscount' field has been set.
      * @return True if the 'promotionDiscount' field has been set, false otherwise.
      */
    public boolean hasPromotionDiscount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'promotionDiscount' field.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder clearPromotionDiscount() {
      promotionDiscount = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'staffDiscount' field.
      * @return The value.
      */
    public java.lang.CharSequence getStaffDiscount() {
      return staffDiscount;
    }

    /**
      * Sets the value of the 'staffDiscount' field.
      * @param value The value of 'staffDiscount'.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder setStaffDiscount(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.staffDiscount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'staffDiscount' field has been set.
      * @return True if the 'staffDiscount' field has been set, false otherwise.
      */
    public boolean hasStaffDiscount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'staffDiscount' field.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder clearStaffDiscount() {
      staffDiscount = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'newPrice' field.
      * @return The value.
      */
    public java.lang.CharSequence getNewPrice() {
      return newPrice;
    }

    /**
      * Sets the value of the 'newPrice' field.
      * @param value The value of 'newPrice'.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder setNewPrice(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.newPrice = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'newPrice' field has been set.
      * @return True if the 'newPrice' field has been set, false otherwise.
      */
    public boolean hasNewPrice() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'newPrice' field.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder clearNewPrice() {
      newPrice = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'promotionType' field.
      * @return The value.
      */
    public java.lang.CharSequence getPromotionType() {
      return promotionType;
    }

    /**
      * Sets the value of the 'promotionType' field.
      * @param value The value of 'promotionType'.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder setPromotionType(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.promotionType = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'promotionType' field has been set.
      * @return True if the 'promotionType' field has been set, false otherwise.
      */
    public boolean hasPromotionType() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'promotionType' field.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder clearPromotionType() {
      promotionType = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'promotionDescription' field.
      * @return The value.
      */
    public java.lang.CharSequence getPromotionDescription() {
      return promotionDescription;
    }

    /**
      * Sets the value of the 'promotionDescription' field.
      * @param value The value of 'promotionDescription'.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder setPromotionDescription(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.promotionDescription = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'promotionDescription' field has been set.
      * @return True if the 'promotionDescription' field has been set, false otherwise.
      */
    public boolean hasPromotionDescription() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'promotionDescription' field.
      * @return This builder.
      */
    public com.acme.avro.priceModifier.Builder clearPromotionDescription() {
      promotionDescription = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public priceModifier build() {
      try {
        priceModifier record = new priceModifier();
        record.promotionCode = fieldSetFlags()[0] ? this.promotionCode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.partnerCode = fieldSetFlags()[1] ? this.partnerCode : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.promotionDiscount = fieldSetFlags()[2] ? this.promotionDiscount : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.staffDiscount = fieldSetFlags()[3] ? this.staffDiscount : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.newPrice = fieldSetFlags()[4] ? this.newPrice : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.promotionType = fieldSetFlags()[5] ? this.promotionType : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.promotionDescription = fieldSetFlags()[6] ? this.promotionDescription : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<priceModifier>
    WRITER$ = (org.apache.avro.io.DatumWriter<priceModifier>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<priceModifier>
    READER$ = (org.apache.avro.io.DatumReader<priceModifier>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
