/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.acme.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class promotionRedemption_record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4626448747799547971L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"promotionRedemption_record\",\"namespace\":\"com.acme.avro\",\"fields\":[{\"name\":\"promotionCode\",\"type\":\"string\"},{\"name\":\"partnerCode\",\"type\":\"string\"},{\"name\":\"redemptionQuantity\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<promotionRedemption_record> ENCODER =
      new BinaryMessageEncoder<promotionRedemption_record>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<promotionRedemption_record> DECODER =
      new BinaryMessageDecoder<promotionRedemption_record>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<promotionRedemption_record> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<promotionRedemption_record> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<promotionRedemption_record>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this promotionRedemption_record to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a promotionRedemption_record from a ByteBuffer. */
  public static promotionRedemption_record fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence promotionCode;
  @Deprecated public java.lang.CharSequence partnerCode;
  @Deprecated public int redemptionQuantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public promotionRedemption_record() {}

  /**
   * All-args constructor.
   * @param promotionCode The new value for promotionCode
   * @param partnerCode The new value for partnerCode
   * @param redemptionQuantity The new value for redemptionQuantity
   */
  public promotionRedemption_record(java.lang.CharSequence promotionCode, java.lang.CharSequence partnerCode, java.lang.Integer redemptionQuantity) {
    this.promotionCode = promotionCode;
    this.partnerCode = partnerCode;
    this.redemptionQuantity = redemptionQuantity;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return promotionCode;
    case 1: return partnerCode;
    case 2: return redemptionQuantity;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: promotionCode = (java.lang.CharSequence)value$; break;
    case 1: partnerCode = (java.lang.CharSequence)value$; break;
    case 2: redemptionQuantity = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'promotionCode' field.
   * @return The value of the 'promotionCode' field.
   */
  public java.lang.CharSequence getPromotionCode() {
    return promotionCode;
  }

  /**
   * Sets the value of the 'promotionCode' field.
   * @param value the value to set.
   */
  public void setPromotionCode(java.lang.CharSequence value) {
    this.promotionCode = value;
  }

  /**
   * Gets the value of the 'partnerCode' field.
   * @return The value of the 'partnerCode' field.
   */
  public java.lang.CharSequence getPartnerCode() {
    return partnerCode;
  }

  /**
   * Sets the value of the 'partnerCode' field.
   * @param value the value to set.
   */
  public void setPartnerCode(java.lang.CharSequence value) {
    this.partnerCode = value;
  }

  /**
   * Gets the value of the 'redemptionQuantity' field.
   * @return The value of the 'redemptionQuantity' field.
   */
  public java.lang.Integer getRedemptionQuantity() {
    return redemptionQuantity;
  }

  /**
   * Sets the value of the 'redemptionQuantity' field.
   * @param value the value to set.
   */
  public void setRedemptionQuantity(java.lang.Integer value) {
    this.redemptionQuantity = value;
  }

  /**
   * Creates a new promotionRedemption_record RecordBuilder.
   * @return A new promotionRedemption_record RecordBuilder
   */
  public static com.acme.avro.promotionRedemption_record.Builder newBuilder() {
    return new com.acme.avro.promotionRedemption_record.Builder();
  }

  /**
   * Creates a new promotionRedemption_record RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new promotionRedemption_record RecordBuilder
   */
  public static com.acme.avro.promotionRedemption_record.Builder newBuilder(com.acme.avro.promotionRedemption_record.Builder other) {
    return new com.acme.avro.promotionRedemption_record.Builder(other);
  }

  /**
   * Creates a new promotionRedemption_record RecordBuilder by copying an existing promotionRedemption_record instance.
   * @param other The existing instance to copy.
   * @return A new promotionRedemption_record RecordBuilder
   */
  public static com.acme.avro.promotionRedemption_record.Builder newBuilder(com.acme.avro.promotionRedemption_record other) {
    return new com.acme.avro.promotionRedemption_record.Builder(other);
  }

  /**
   * RecordBuilder for promotionRedemption_record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<promotionRedemption_record>
    implements org.apache.avro.data.RecordBuilder<promotionRedemption_record> {

    private java.lang.CharSequence promotionCode;
    private java.lang.CharSequence partnerCode;
    private int redemptionQuantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.acme.avro.promotionRedemption_record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.promotionCode)) {
        this.promotionCode = data().deepCopy(fields()[0].schema(), other.promotionCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.partnerCode)) {
        this.partnerCode = data().deepCopy(fields()[1].schema(), other.partnerCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.redemptionQuantity)) {
        this.redemptionQuantity = data().deepCopy(fields()[2].schema(), other.redemptionQuantity);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing promotionRedemption_record instance
     * @param other The existing instance to copy.
     */
    private Builder(com.acme.avro.promotionRedemption_record other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.promotionCode)) {
        this.promotionCode = data().deepCopy(fields()[0].schema(), other.promotionCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.partnerCode)) {
        this.partnerCode = data().deepCopy(fields()[1].schema(), other.partnerCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.redemptionQuantity)) {
        this.redemptionQuantity = data().deepCopy(fields()[2].schema(), other.redemptionQuantity);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'promotionCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getPromotionCode() {
      return promotionCode;
    }

    /**
      * Sets the value of the 'promotionCode' field.
      * @param value The value of 'promotionCode'.
      * @return This builder.
      */
    public com.acme.avro.promotionRedemption_record.Builder setPromotionCode(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.promotionCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'promotionCode' field has been set.
      * @return True if the 'promotionCode' field has been set, false otherwise.
      */
    public boolean hasPromotionCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'promotionCode' field.
      * @return This builder.
      */
    public com.acme.avro.promotionRedemption_record.Builder clearPromotionCode() {
      promotionCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'partnerCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getPartnerCode() {
      return partnerCode;
    }

    /**
      * Sets the value of the 'partnerCode' field.
      * @param value The value of 'partnerCode'.
      * @return This builder.
      */
    public com.acme.avro.promotionRedemption_record.Builder setPartnerCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.partnerCode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'partnerCode' field has been set.
      * @return True if the 'partnerCode' field has been set, false otherwise.
      */
    public boolean hasPartnerCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'partnerCode' field.
      * @return This builder.
      */
    public com.acme.avro.promotionRedemption_record.Builder clearPartnerCode() {
      partnerCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'redemptionQuantity' field.
      * @return The value.
      */
    public java.lang.Integer getRedemptionQuantity() {
      return redemptionQuantity;
    }

    /**
      * Sets the value of the 'redemptionQuantity' field.
      * @param value The value of 'redemptionQuantity'.
      * @return This builder.
      */
    public com.acme.avro.promotionRedemption_record.Builder setRedemptionQuantity(int value) {
      validate(fields()[2], value);
      this.redemptionQuantity = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'redemptionQuantity' field has been set.
      * @return True if the 'redemptionQuantity' field has been set, false otherwise.
      */
    public boolean hasRedemptionQuantity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'redemptionQuantity' field.
      * @return This builder.
      */
    public com.acme.avro.promotionRedemption_record.Builder clearRedemptionQuantity() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public promotionRedemption_record build() {
      try {
        promotionRedemption_record record = new promotionRedemption_record();
        record.promotionCode = fieldSetFlags()[0] ? this.promotionCode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.partnerCode = fieldSetFlags()[1] ? this.partnerCode : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.redemptionQuantity = fieldSetFlags()[2] ? this.redemptionQuantity : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<promotionRedemption_record>
    WRITER$ = (org.apache.avro.io.DatumWriter<promotionRedemption_record>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<promotionRedemption_record>
    READER$ = (org.apache.avro.io.DatumReader<promotionRedemption_record>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
